site_name: OpenCTI Documentation
site_description: Documentation about OpenCTI, the next-generation Cyber Threat Intelligence platform.
site_author: Filigran
site_url: https://docs.opencti.io
copyright: © 2023 Filigran. All rights reserved
repo_name: GitHub
repo_url: https://github.com/OpenCTI-Platform/opencti
edit_uri: https://github.com/OpenCTI-Platform/docs/blob/main/docs/

# Theming
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.path
    - navigation.footer
    - navigation.expand
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - search.highlight
  palette:
    scheme: filigran
  font:
    text: IBM Plex Sans
    code: Roboto Mono
# CSS
extra_css:
  - assets/css/custom.css

# Extra
extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-DB4K9LZPDZ
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OpenCTI-Platform
    - icon: fontawesome/brands/medium
      link: https://blog.filigran.io
    - icon: fontawesome/brands/slack
      link: https://community.filigran.io
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/filigran
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FiligranHQ
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/FiligranHQ

# Plugins
plugins:
  - search
  - git-committers:
      repository: OpenCTI-Platform/docs
      branch: main  
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - glightbox

# Extensions
markdown_extensions: 
  - attr_list
  - md_in_html
  - tables
  - admonition   
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true   
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: false
      auto_title: false
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg   
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      url_download: true

# Page tree
nav:
  - Home: 'index.md'
  - Deployment & Setup:
    - Platform:
      - Overview: deployment/overview.md
      - Installation: deployment/installation.md
      - Configuration: deployment/configuration.md
      - Authentication: deployment/authentication.md
      - Upgrade: deployment/upgrade.md
    - Ecosystem:
      - Connectors: deployment/connectors.md
      - Integrations: deployment/integrations.md
      - Third-party: deployment/third-party.md
  - User Guide:
    - Structure:
      - Platform organization: usage/platform.md
      - Create knowledge: usage/knowledge.md
      - Cases and reports: usage/cases-reports.md
      - Import and export: usage/import-export.md
    - Main Features:
      - Enrichment: usage/enrichment.md
      - Notifications and alerting: usage/notifications.md
      - Custom dashboards: usage/dashboards.md
      - Investigations: usage/investigations.md
    - Activities:
      - Import from documents: usage/documents.md
      - Managing duplicates: usage/duplicates.md    
  - Administration:
    - General:
      - Parameters: administration/parameters.md
      - Engines and schedulers: administration/engines.md
      - Retention policies: administration/retention.md
    - Security:
      - Authentication and RBAC: administration/rbac.md
      - Data segregation: administration/segregation.md
      - Audit and monitoring: administration/audit.md
    - Troubleshooting: administration/troubleshooting.md
  - Reference:
    - Data model: reference/data-model.md
    - GraphQL API: reference/api.md
    - Events streaming: reference/streaming.md
    - Security: reference/security.md
  - Development:
    - Environment setup: development/environment.md
    - Connectors development: development/connectors.md